### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by losolio** [losol/converto#1]
As converto I can take raw html or url to an html page as input and generate an pdf file from the html so that I can send the html as a pdf. 

The pdf generator cut take the document to be converted in the following formats: 
* raw html, OR
* an url to a html page

It could take the following optional options:
* scale <number> Scale of the webpage rendering. Defaults to 1. Scale amount must be between 0.1 and 2.
* format <string> Paper format. If set, takes priority over width or height options. Defaults to 'A4'.

Acceptance criteria
* The PDF generated should be readable by common PDF readers as Acrobat
* The PDF generation should be done be done by the [puppeteer library](https://github.com/puppeteer/puppeteer).
* No files should be stored as files on the server after job has finished

**Comment by andy-a-o** [comment]
Should be done in https://github.com/losol/converto/pull/7
