### ISSUE TITLE
REST API for html to pdf conversion

### ISSUE THREAD

**Issue by losolio** [losol/converto#3]
As an external client I can send an url to converto and have it returned as a pdf. 

We are considering building this as a [Strapi plugin](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/quick-start.html), and let Strapi handling auth. 

The API should be reached at
`/api/v1/convert/html2pdf`

Required parameters
* **url** the url to the html page to be converted, **OR**
* **html** the raw html to be converted

Required header parameters
* **apikey** the api key for access to the service

Optional parameters
* **scale** Scale of the webpage rendering. Defaults to 1. Scale amount must be between 0.1 and 2.
* **format** Paper format. If set, takes priority over width or height options. Defaults to 'A4'.

**Comment by andy-a-o** [comment]
Should be done in https://github.com/losol/converto/pull/7

Two methods are supported:

`GET /api/v1/convert/html2pdf?url=` - to generate PDF from URL
`POST /api/v1/convert/html2pdf` - to generate PDF from POSTed HTML.

Both methods accept two optional query params: `scale` and `format`, just as described above.
Both methods require `Authorization: Bearer <JWT token>` header.
POST method requires HTML content to be POSTed with `Content-Type: text/plain` header set.
