### ISSUE TITLE
Securing html2pdf API

### ISSUE THREAD

**Issue by losolio** [losol/converto#4]
To ensure the API is only used of atuhorized users we should have a permission so that only users with a certain role are allowed to use the html2pdf api endpoint.

**Comment by andy-a-o** [comment]
Should be done in https://github.com/losol/converto/pull/7

Plugin auth is working out of the box, you'd need to put some checkmarks against plugin API methods for the specific role. 

![image](https://user-images.githubusercontent.com/21310402/71360614-7f10ef00-25a1-11ea-92a5-68ca08b7a214.png)
