### ISSUE TITLE
Upgrade all dependencies

### ISSUE THREAD

**Issue by losolio** [losol/converto#44]
The project's package.json file contains several outdated dependencies that may cause security vulnerabilities, compatibility issues, or performance problems. It is recommended to upgrade all dependencies to their latest versions and test the functionality of the application.

## Steps to reproduce

- Run `npm outdated` in the project directory to see the list of outdated dependencies
- Run `npm install --save-dev npm-check-updates` to install a tool that can update the package.json file automatically
- Run `npx npm-check-updates -u` to upgrade all dependencies to their latest versions
- Run `npm install` to install the updated dependencies
- Run `npm test` to check if the application works as expected

## Expected behavior

The application should run without errors.

## Actual behavior

The application is running but there is some security risks.

**Comment by meinte** [comment]
Started work on this
additionally:
- will run `npm audit` to see any other advisories (and attempt an audit fix)
- will update package lock versioning

**Comment by meinte** [comment]
Since Strapi v3 is no longer maintained, it would make sense to update the plugin to whatever v4 accepts, which would include a rewrite.

**Comment by losolio** [comment]
@meinte sorry that this was unclear, but I think it is a good idea to upgrade also to the latest major version for all packages!

**Comment by meinte** [comment]
Not a problem, though be prepared for a PR with a lot of changes :)

**Comment by meinte** [comment]
Strongly suggest to use a PDF generator library (I have used pdftk succesfully in the past) instead of puppeteer. Puppeteer has a footprint much larger than a 'standalone' pdf library, besides that using puppeteer out of sandbox mode is a serious security issue (the heroku fix). This PR also does not include additional typing for the controller and service, that should be tackled with the other issue but will take a little more time.

**Comment by losolio** [comment]
Thanks for your comment @meinte. I am open to change libraries for generating pdfs, however not sure if pdftk alone will render html? The html sent to this may contain base encoded images, urls to images and so on.. We have taken some measures on the security issue by isolating this service to an isolated db and app server, but are totally open to enhance the security!

**Comment by meinte** [comment]
ah yes - you could always wrap into a highly restricted docker image, but if it is isolated already that may already be good enough - it all depends whether you want this plugin to be used by others as well.

**Comment by losolio** [comment]
Thanks for your suggestion, @meinte  - I just lifted it out to a separate issue: #48
