### ISSUE TITLE
Convert the project to Typescript

### ISSUE THREAD

**Issue by losolio** [losol/converto#45]
## Description

The project is currently written in plain Javascript, which may cause type errors, bugs, or readability issues. It is suggested to convert the project to Typescript, a superset of Javascript that adds static type checking and other features. This would improve the code quality, maintainability, and developer experience of the project.

## Expected behavior

The project should be fully converted to Typescript and run without errors or warnings.

**Comment by meinte** [comment]
Picking this up today - should not take more than 2 hours 

- Typesafe service and controller
- Typed requests and responses (using zod)
- Unit tests for service and controller (testing mainly responses and error handling, not the PDF output)

**Comment by losolio** [comment]
Thanks @meinte, just go ahead 😀
